//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;
using System.Xml.Serialization;
namespace BloodDonation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationForSystem
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int DonationId { get; set; }
        public double Amount { get; set; }
        public string MoneySource { get; set; }
        public string Name { get; set; }
        public string UserEmail { get; set; }
        public string YourMessage { get; set; }
    }
}
