//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;
using System.Xml.Serialization;
namespace BloodDonation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestBlood
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int RequestId { get; set; }
        public string Request_Message { get; set; }
        public int UserId { get; set; }
        public int DonarId { get; set; }

        /* public virtual RequestBlood RequestBlood1 { get; set; }
         public virtual RequestBlood RequestBlood2 { get; set; }*/

  /*      public virtual userinfo userInfo { get; set; }

        public virtual userinfo userInfo1 { get; set; }*/
    }
}
